package com.iot.lab.enums;

public enum Services {
    COMPANY_REGISTRATION,
    PROVIDING_CONSULTATION,
    BUSINESS_PAPERS_PREPARATION,
    FIRM_RESALE_GUARANTEE,
    ASSISTANCE_IN_REAL_ESTATE_TRANSACTIONS,
    APPLICATION_REGISTRATION,
    COPYRIGHT_REGISTRATION_AND_PROTECTION,
    CONSULTATION,
    COURT_PROCEEDINGS
}
